AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an AWS WorkMail Organization and User

Parameters:
  OrganizationName:
    Type: String
    Description: The name of the WorkMail organization
  DomainName:
    Type: String
    Description: The custom domain name for the WorkMail organization
  UserName:
    Type: String
    Description: The username for the WorkMail user
  DisplayName:
    Type: String
    Description: The display name of the WorkMail user
  Password:
    Type: String
    Description: The password for the WorkMail user
  FirstName:
    Type: String
    Description: The first name of the WorkMail user
  LastName:
    Type: String
    Description: The last name of the WorkMail user

Resources:
  WorkMailOrganization:
    Type: AWS::WorkMail::Organization
    Properties:
      Alias: !Ref OrganizationName
      DirectoryId: null # Set this if you're using AWS Managed AD; otherwise, leave as null
      EnableInteroperability: false

  WorkMailDomain:
    Type: AWS::WorkMail::Domain
    Properties:
      OrganizationId: !Ref WorkMailOrganization
      DomainName: !Ref DomainName

  WorkMailUser:
    Type: AWS::WorkMail::User
    Properties:
      OrganizationId: !Ref WorkMailOrganization
      Name: !Ref UserName
      DisplayName: !Ref DisplayName
      Password: !Ref Password

Outputs:
  OrganizationId:
    Description: The ID of the created WorkMail organization
    Value: !Ref WorkMailOrganization

  UserEmail:
    Description: The email address of the created WorkMail user
    Value: !Sub "${UserName}@${DomainName}"
